version: '3.9'

networks:
  check24-net:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myblog
    networks:
      - check24-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blog:
    build:
      context: .
      dockerfile: Dockerfile.blog
    container_name: blog
    networks:
      - check24-net
    ports:
      - "8085:8085"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    environment:
      - BLOG_CONFIG_PATH=config/blog/prod.yaml

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: admin
    networks:
      - check24-net
    ports:
      - "8086:8086"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data_source:
    driver: local
